[project]
name = "vibehacker-metasploit-mcp"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "paramiko>=3.5.1",
    "pymetasploit3>=1.0.6",
    "pytest>=8.3.5",
]
